---
title: "Type I error and false discovery rate (FDR) per sample test"
author: "Quang Nguyen"
date: "9/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulating data 


```{r loading, echo = F}
source("../R/simulations.R")
source("../R/utils.R")
sourceCpp("../src/get_s_matrix.cpp")
```

```{r generate_data}
calibration <- readRDS(file = "../data/hmp_stool_calibration.rds")
calibration <- sort(calibration, decreasing = T)
top_300 <- calibration[1:300]
dm_simulation(template = top_300, n_samp = 100, spar = 0.2)


base_param <- list(
  nsamp = c(100,100,300),
  spar = c(0.2, 0.5, 0.9)
)

inf_param <- list(
  eff_size = c(2,4,6,8), 
  n_inflate = 30
)

sim <- cross_df(base_param)

sim$data_idx <- seq(nrow(sim))

sim %>% group_by(data_idx) %>% nest() %>% transmute(base_param = data) %>% 
  mutate(sim_data = map(data,.f = pmap()))
cross_df(base_param)

test <- cross_df(param)
test$model <- seq(nrow(test))

test <- test %>% group_by(model) %>% nest() %>% transmute(param = data)

```





