---
title: "Power simulations at the single sample level"
author: "Quang Nguyen"
date: "10/7/2020"
output: html_document
  toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading parameters and simulated data sets  

```{r loadings, message=FALSE, warning=FALSE}
library(tidyverse)
library(furrr)
library(tictoc)
library(MASS)
library(ggsci)
library(progressr)
library(patchwork)
source("cilr.R")
source("simulations.R")
source("utils.R")

# object file is large and not included. 
parameters <- readRDS(file = "../objects/auc_sim/parameters.rds")
```

# Score estimation 

Estimating scores using `furrr` package.  

```{r estimate_scores, cache=TRUE, message = FALSE, warning=FALSE}
tic()
plan(multiprocess, workers = round(availableCores()/2,0))
with_progress({
  p <- progressor(steps = nrow(parameters))
  parameters$scores_cilr <- future_map(1:nrow(parameters), .f = ~{
    p()
    data <- readRDS(file = glue("../objects/auc_sim/simulation_{.x}"))
    simple_cilr(X = data$X, A = data$A, preprocess = T, pcount = 1)
  })
})
plan(sequential)
toc()


plan(multiprocess, workers = round(availableCores()/2,0))
with_progress({
  p <- progressor(steps = nrow(parameters))
  parameters$scores_gsva_pois <- future_map(1:nrow(parameters), .f = ~{
    p()
    data <- readRDS(file = glue("../objects/auc_sim/simulation_{.x}"))
    generate_alt_scores(X = data$X, A = data$A, method = "gsva", preprocess = T, transform=NULL, pcount=1)
  })
})
plan(sequential)

plan(multiprocess, workers = round(availableCores()/2,0))
with_progress({
  p <- progressor(steps = nrow(parameters))
  parameters$scores_gsva_gauss <- future_map(1:nrow(parameters), .f = ~{
    p()
    data <- readRDS(file = glue("../objects/auc_sim/simulation_{.x}"))
    generate_alt_scores(X = data$X, A = data$A, method = "gsva", preprocess = T, transform="clr", pcount=1)
  })
})
plan(sequential)

plan(multiprocess, workers = round(availableCores()/2,0))
with_progress({
  p <- progressor(steps = nrow(parameters))
  parameters$scores_ssgsea <- future_map(1:nrow(parameters), .f = ~{
    p()
    data <- readRDS(file = glue("../objects/auc_sim/simulation_{.x}"))
    generate_alt_scores(X = data$X, A = data$A, method = "ssgsea", preprocess = T, transform=NULL, pcount=1)
  })
})
plan(sequential)


plan(multiprocess, workers = round(availableCores()/2,0))
with_progress({
  p <- progressor(steps = nrow(parameters))
  parameters$scores_prop <- future_map(1:nrow(parameters), .f = ~{
    p()
    data <- readRDS(file = glue("../objects/auc_sim/simulation_{.x}"))
    generate_alt_scores(X = data$X, A = data$A, method = "prop", preprocess = T, transform="prop", pcount=1)
  })
})
plan(sequential)
```

After estimating scores, we can generate labels using various ways 
```{r generate_labels, warning = FALSE, message = FALSE, cache = T}
# generating labels with threshold 
# using raw scores and standard normal distribution  

parameters$label_cilr_raw <- map(parameters$scores_cilr, .f = ~cilr_eval(scores = .x, alt = "greater", 
                                                                         thresh = 0.05, resample = F, 
                                                                         return = "sig"))
opt <- furrr_options(seed = T)
plan(multisession, workers = round(availableCores()/2,0))
parameters$label_cilr_norm <- future_map(1:nrow(parameters), .f = ~{
  data <- readRDS(file = glue("../objects/pwr_sim/simulation_{i}.rds",i = .x))
  cilr_eval(scores = parameters$scores_cilr[[.x]], 
            distr = "norm", alt = "greater", thresh = 0.05, resample = T, 
            X = data$X, A = data$A, return = "sig")
}, .options = opt, .progress = T)
plan(sequential)

plan(multisession, workers = round(availableCores()/2,0))
parameters$label_cilr_t <- future_map(1:nrow(parameters), .f = ~{
  data <- readRDS(file = glue("../objects/pwr_sim/simulation_{i}.rds", i = .x))
  cilr_eval(scores = parameters$scores_cilr[[.x]], 
            distr = "t", alt = "greater", thresh = 0.05, resample = T, 
            X = data$X, A = data$A, return = "sig")
}, .options = opt, .progress = T)
plan(sequential)



# generating fdr comparable statistics 
parameters$fdr_cilr_raw <- map(parameters$label_cilr_raw, .f = ~calculate_statistic(eval = "pwr", pred = .x, 
                                                                                    true = rep(1, length(.x))))
parameters$fdr_cilr_norm <- map(parameters$label_cilr_norm, .f = ~calculate_statistic(eval = "pwr", pred = .x, 
                                                                                      true = rep(1, length(.x))))
parameters$fdr_wc <- map(parameters$label_wc, .f = ~calculate_statistic(eval = "pwr", pred = .x, 
                                                                        true = rep(1, length(.x))))
parameters$fdr_cilr_t <- map(parameters$label_cilr_t, .f = ~calculate_statistic(eval = "pwr", pred = .x,
                                                                                true = rep(1, length(.x))))
```



## Plots 

```{r evaluation_plots}
plot_df <- parameters %>% unnest(starts_with("fdr")) %>% 
  dplyr::select(!starts_with(c("label", "scores", "sim"))) %>% 
  pivot_longer(starts_with("fdr")) %>% group_by(b_spar, b_rho, eff_size, name) %>% 
  summarise(median = median(value), lower = median(value) - sd(value), 
            upper = median(value) + sd(value))

plot_df <- plot_df %>% dplyr::rename("Effect Size" = "eff_size", "Inter-taxa Correlation" = "b_rho")
print(head(plot_df))
#plot_df <- plot_df %>% filter(name != "fdr_cilr_resample")
plt <- ggplot(plot_df, aes(y = median, x = as.factor(b_spar), col = name, group = name)) + geom_point(size = 3) +
  scale_color_nejm(labels = c("cILR normal", "cILR raw", "cILR t", "Wilcoxon Rank Sum")) + 
  geom_line() + geom_hline(yintercept = 0.8, col = "red") +
  geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.06, size = 1.2) +
  facet_grid(`Inter-taxa Correlation` ~ `Effect Size`, scales = "free_y", labeller = label_both) +
  labs(col = "Evaluation Models", x = "Sparsity", y = "Median Power \n (100 data sets, N = 1000, alpha = 0.05)") + 
  theme_bw()
plt

ggsave(plt, filename = "docs/manuscript/figures/pwr_single_sample.png", 
       dpi = 300, width = 10, height = 10)
```
