---
title: "Estimating Parameters from HMP data"
author: "Quang Nguyen"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setting up 
```{r}
library(tidyverse)
library(VGAM)
library(edgeR)
library(patchwork)
library(HMP16SData)
library(phyloseq)
library(glue)
library(modelr)
data <- V35() %>% subset(select = HMP_BODY_SUBSITE == "Stool" & VISITNO == 1) %>% as_phyloseq()
data <- subset_samples(data,!duplicated(RSID)) %>% 
  filter_taxa(function(x) (sum(x == 0)/length(x)) < 0.9, TRUE)
data <- prune_samples(sample_sums(data) >= 1000, data)
data_param <- list(log_mu = log1p(rowMeans(data@otu_table@.Data)), 
                   pstr0 = rowMeans(data@otu_table@.Data == 0))
```

# Estimate negative binomial distribution for non-zero values  
```{r, message = F, warning=F}
results <- vector(mode = "list", length = ntaxa(data))

for (i in 1:nrow(data@otu_table@.Data)){
  nonzero <- as.vector(data@otu_table@.Data[i,which(data@otu_table@.Data[i,] != 0)])
  results[[i]] <- fitdistrplus::fitdist(nonzero, distr = "nbinom")$estimate
}

results <- do.call(rbind, results)
results <- as.data.frame(results)

saveRDS(results, file = "fitted_value_nonzero.rds")
p1 <- qplot(results$size, geom = "histogram", xlim = c(1,5), fill = I("steelblue"), col = I("black")) + 
  geom_vline(aes(xintercept = median(results$size)), size = 1.5, col = "red") + theme_bw() + 
  labs(x = "Size", y = "Frequency") + 
  annotate("text", x = 1.8, y = 150, label = glue("Median = {med}", med = round(median(results$size),2)), hjust = 0)

p2 <- qplot(results$mu, geom = "histogram", xlim = c(0,10), fill = I("steelblue"), col = I("black")) + 
  geom_vline(aes(xintercept = median(results$mu)), size = 1.5, col = "red") + theme_bw() + 
  labs(x = "Mean", y = "Frequency") + 
  annotate("text", x = 3.3, y = 300, label = glue("Median = {med}", med = round(median(results$mu),2)), hjust = 0)

plt <- p1 + p2
# ggsave(plt, filename = "docs/manuscript/figures/HMP_fit_nonzero.png", dpi = 300, width = 8, height = 8)
```

# Estimate negative binomial distribution for all values (approximate real data)  

```{r}
counts <- data@otu_table@.Data
design <- model.matrix(~1, data = data.frame(data@sam_data))
normFacts <- edgeR::calcNormFactors(counts, method = "TMM")
dge <- DGEList(counts = counts)
dge$samples$norm.factors <- normFacts
disp <- estimateDisp(y = dge, design = design, tagwise = TRUE)
fit <- glmFit(dge$counts,dispersion = disp$tagwise.dispersion, design = design)

mean <- rowMeans(fit$fitted.values)
size <- 1/disp$tagwise.dispersion
pstr0 <- rowMeans((1+fit$fitted.values*disp$tagwise.dispersion)^(-1/disp$tagwise.dispersion))
result <- as.data.frame(cbind(mean,size,pstr0))
result$log_mu <- log1p(mean)
saveRDS(result, file = "fitted_value_complete.rds")
print("Median values for each parameter")
apply(result, 2, median)
```

## Plotting values 
```{r}
p1 <- qplot(result$size, geom = "histogram", fill = I("steelblue"), col = I("black")) + 
  geom_vline(aes(xintercept = median(result$size)), size = 1.5, col = "red") + theme_bw() + 
  labs(x = "Size", y = "Frequency") + 
  annotate("text", x = 0.2, y = 1000, label = glue("Median = {med}", med = round(median(result$size),2)), hjust = 0)

p2 <- qplot(result$mu, geom = "histogram", xlim = c(0,5), fill = I("steelblue"), col = I("black")) + 
  geom_vline(aes(xintercept = median(result$mu)), size = 1.5, col = "red") + theme_bw() + 
  labs(x = "Mean", y = "Frequency") + 
  annotate("text", x = 0.72, y = 1500, label = glue("Median = {med}", med = round(median(result$mu),2)), hjust = 0)

p3 <- qplot(result$pstr0, geom = "histogram", xlim = c(0,1), fill = I("steelblue"), col = I("black")) + 
  geom_vline(aes(xintercept = median(result$pstr0)), size = 1.5, col = "red") + theme_bw() + 
  labs(x = "pstr0", y = "Frequency") + 
  annotate("text", x = 0.83, y = 1000, label = glue("Median = {med}", med = round(median(result$pstr0),2)), hjust = 0)

fitting_plot <- (p1 / p2 / p3) + plot_annotation(tag_levels = "A")
fitting_plot
#ggsave(fitting_plot, filename = "docs/manuscript/figures/HMP_fit_range.png", dpi = 300, width = 10, height = 10)

```

Plots for fitting this distribution using edgeR  
```{r}
p1 <- qplot(y = result$log_mu, x = data_param$log_mu, geom = "point", col = I("steelblue")) + theme_bw() + 
  annotate("text", x = 1, y = 4, label = glue("R-squared: {value}", 
                                                   value = round(cor(data_param$log_mu, result$log_mu)^2,2))) + 
    annotate("text", x = 1, y = 3.75, label = glue("RMSE: {value}", 
                                                   value = round(rmse(data_param$log_mu, result$log_mu),3))) + 
  labs(y = "Fitted Mean", x = "Sample Mean") + geom_smooth(method = "glm")
p2 <- qplot(y = result$pstr0, x = data_param$pstr0, geom = "point", col = I("steelblue")) + theme_bw() + 
  annotate("text", x = 0.25, y = 0.75, label = glue("R-squared: {value}", 
                                                   value = round(cor(data_param$pstr0, result$pstr0)^2,2))) + 
  annotate("text", x = 0.25, y = 0.7, label = glue("RMSE: {value}", 
                                                   value = round(rmse(data_param$pstr0, result$pstr0),3))) + 
  labs(y = "Fitted Zero Proportion", x = "Sample Zero Proportion") + geom_smooth(method = "glm")
evaluate_fit <- p1 + p2
evaluate_fit
#ggsave(evaluate_fit, filename = "docs/manuscript/figures/HMP_fit_evaluation.png", dpi = 300, width = 10, height = 10)

```

