---
title: "Null data evaluation"
author: "Quang Nguyen"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}
library(tidyverse)
library(qs)
library(phyloseq)
library(patchwork)
```

```{r generate_random}
data <- qread(file = "../data/hmp_stool_16S.qs")
labels <- matrix(nrow = nsamples(data), ncol = 1000)
for (i in 1:ncol(labels)){
  labels[,i] <- rbinom(nsamples(data),1,0.5)
}
qsave(labels, "../data/null_16s_labels.qs")
```

```{r evaluate}
methods <- c("cilr_welch", "cilr_wilcox", "gsva_welch", "gsva_wilcox", "corncob", "deseq2", "clr_welch",
             "clr_wilcox", "ancombc")
prop <- vector(mode = "list", length = length(methods))
for (i in 1:length(methods)){
  filename <- glue("../objects/hmp_stool_16S/type_i_{method}.qs", method = methods[i])
  data <- qread(file = filename)
  counts <- sapply(1:ncol(data), function(x) sum(data[,x] == 1))
  prop[[i]] <- counts/nrow(data)
}


summary <- tibble(methods = methods, prop = prop)
summary$mean <- sapply(prop, mean, na.rm = T)
summary$max <- sapply(prop, function(x){
  value <- mean(x, na.rm = T) + sd(x, na.rm = T)
  return(value)
})
summary$min <- sapply(prop, function(x){
  value <- mean(x, na.rm = T) - sd(x, na.rm = T)
  value <- ifelse(value < 0, 0, value)
  return(value)
})


p1 <- ggplot(summary %>% filter(!methods %in% c("corncob", "deseq2")), aes(x = methods, y = mean, col = methods)) + geom_point(size = 4) + geom_errorbar(aes(ymax = max, ymin = min)) + coord_flip() + scale_color_nejm() + 
  theme_bw() + theme(legend.position = "none", axis.title.y = element_blank()) + labs(y = "Type I error")
p2 <- ggplot(summary %>% filter(methods %in% c("corncob", "deseq2")), aes(x = methods, y = mean, col = methods)) + geom_point(size = 4) + geom_errorbar(aes(ymax = max, ymin = min)) + scale_color_nejm() + coord_flip() + 
  theme_bw() + theme(legend.position = "none", axis.title.y = element_blank(), axis.title.x = element_blank())
layout <- c(
  area(t = 3, l = 1, b = 6, r = 4), 
  area(t = 1, l = 1, b = 2, r = 4)
)
plot_16S <- (p1 / p2) + plot_layout(design = layout, guides = 'collect')
```
