---
title: "Plotting"
author: "Quang Nguyen"
date: "10/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting up packages  
```{r package_load}
library(tidyverse)
library(ggsci)
library(qs)
library(patchwork)
library(binom)
```

## Plotting  

```{r fdr_evaluation}
parameters <- qread("../objects/fdr_ss_eval.qs")

plot_df <- parameters %>% unnest(starts_with("fdr")) %>% 
  dplyr::select(!starts_with(c("label", "scores", "sim"))) %>% dplyr::select(!starts_with("fdr_se")) %>% 
  pivot_longer(starts_with("fdr")) %>% group_by(spar, s_rho, n_inflate, name)

plot_df <- plot_df %>% mutate(mean = ifelse(is.na(value), NA, binom.confint(value, 2e4, conf.level = 0.95, methods = "ac")$mean), 
                  upper = ifelse(is.na(value), NA, binom.confint(value, 2e4, conf.level = 0.95, methods = "ac")$upper),
                  lower = ifelse(is.na(value), NA, binom.confint(value, 2e4, conf.level = 0.95, methods = "ac")$lower))


plot_df <- plot_df %>% dplyr::rename("Set Size" = "n_inflate", "Inter-taxa Correlation" = "s_rho")
print(head(plot_df))

plt <- ggplot(plot_df, aes(y = mean, x = as.factor(spar), col = name, group = name)) + geom_point() +
  scale_color_npg(labels = c("Mixture normal", "Adj. mixture normal", "normal", "Adj. normal", "Wilcoxon Rank Sum")) + 
  geom_line() + geom_hline(yintercept = 0.05, col = "red") +
  geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.3) +
  facet_grid(`Inter-taxa Correlation` ~ `Set Size`, scales = "free_y", labeller = label_both) +
  labs(col = "Evaluation Models", x = "Sparsity", y = "Type I error \n (N = 20,000, alpha = 0.05)") + 
  theme_bw()
plt

#ggsave(plt, filename = "docs/manuscript/figures/fdr_single_sample.png", dpi = 300, width = 10, height = 10)


# plot_df <- parameters %>% dplyr::select(-starts_with(c('scores', 'label'))) %>% unnest(starts_with("fdr")) %>%  pivot_longer(starts_with("fdr_se")) %>% mutate(type = case_when(str_detect(name, "emp")~ "Empirical",
#                               str_detect(name, "theo") ~ "Theoretical")) %>% 
#   mutate(model = case_when(str_detect(name, "cilr_raw") ~ "cILR Raw",
#                            str_detect(name, "cilr_norm") ~ "cILR Norm",
#                            str_detect(name, "cilr_t") ~ "cILR t",
#                            str_detect(name, "wc") ~ "Wilcox"))
# 
# estimates_plt <- ggplot(plot_df, aes(x = spar, y = value, col = type, shape = model, group = name)) + geom_point() + geom_line() + facet_grid(n_inflate ~ b_rho) + scale_color_nejm()


```

```{r pwr_evaluation}

parameters <- qread(file = "../objects/pwr_ss_eval.qs")
plot_df <- parameters %>% unnest(starts_with("fdr")) %>% 
  dplyr::select(!starts_with(c("label", "scores"))) %>% 
  pivot_longer(starts_with("pwr")) %>% group_by(spar, s_rho, eff_size, name) %>% unnest(value)

plot_df <- plot_df %>% mutate(mean = ifelse(is.na(value), NA, binom.confint(value, 2e4, conf.level = 0.95, methods = "ac")$mean), 
                  upper = ifelse(is.na(value), NA, binom.confint(value, 2e4, conf.level = 0.95, methods = "ac")$upper),
                  lower = ifelse(is.na(value), NA, binom.confint(value, 2e4, conf.level = 0.95, methods = "ac")$lower))

plot_df <- plot_df %>% dplyr::rename("Effect Size" = "eff_size", "Inter-taxa Correlation" = "s_rho")
print(head(plot_df))
#plot_df <- plot_df %>% filter(name != "fdr_cilr_resample")
plt <- ggplot(plot_df, aes(y = mean, x = as.factor(spar), col = name, group = name)) + geom_point() +
  scale_color_npg(labels = c("Mixture normal", "Adj. mixture normal", "normal", "Adj. normal", "Wilcoxon Rank Sum")) + 
  geom_line() + geom_hline(yintercept = 0.8, col = "red") + 
  geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.3) + 
  facet_grid(`Inter-taxa Correlation` ~ `Effect Size`, scales = "free_y", labeller = label_both) +
  labs(col = "Evaluation Models", x = "Sparsity", y = "Power \n (N = 20000, alpha = 0.05)") + 
  theme_bw()
plt

 #ggsave(plt, filename = "docs/manuscript/figures/pwr_single_sample.png", dpi = 300, width = 10, height = 10)
```
```{r pwr_eval_new}
data <- qread("objects/pwr_sim/samp_eval_pwr.qs")
wc <- data$wc
stat <- data$sim
wc <- do.call(rbind,map(wc, as_tibble))
wc$adj <- rep(FALSE, nrow(wc))
wc$distr <- rep("Wilcoxon", nrow(wc))
wc$id <- unique(stat$id)
wc$spar <- stat$spar


stat <- stat %>% mutate(eval = map(eval, as_tibble)) %>% unnest(eval)
test <- right_join(stat, wc) 

ggplot(stat, aes(y = mean, x = spar)) + geom_point() + geom_line(aes(color = distr, linetype = adj)) + 
  facet_grid(eff_size ~ s_rho, scales = "free")
```

```{r fdr_eval_new}
data <- qread("objects/fdr_sim/samp_eval_fdr.qs")
wc <- data$wc
stat <- data$sim
wc <- do.call(rbind,map(wc, as_tibble))
wc$adj <- rep(FALSE, nrow(wc))
wc$distr <- rep("Wilcoxon", nrow(wc))
wc$id <- unique(stat$id)

left_join(stat, wc)


stat <- stat %>% mutate(eval = map(eval, as_tibble)) %>% unnest(eval)
ggplot(stat, aes(y = mean, x = spar)) + geom_point() + geom_line(aes(color = distr, linetype = adj)) + 
  facet_grid(eff_size ~ s_rho)
```

```{r auc_classifier}
parameters <- qread("../objects/auc_rank_evaluation.qs")
params <- as_tibble(parameters[,'parameters']) %>% dplyr::select(-starts_with('scores'))
results <- parameters[,'auc'] %>% as_tibble() %>% dplyr::select(starts_with('scores'))
plot_df <- cbind(params, results)

plot_df <- plot_df %>% pivot_longer(starts_with('scores')) %>% group_by(b_spar, b_rho, eff_size, name) %>% 
  summarise(median = median(value), lower = median(value) - sd(value), upper = median(value) + sd(value)) %>% 
  dplyr::rename("Effect Size" = "eff_size", "Inter-taxa correlation" = "b_rho")
  
auc_plot <- ggplot(plot_df, aes(x = as.factor(b_spar), y = median, col = name, group = name)) + geom_hline(yintercept = 0.8, col = "red") + 
  geom_point(size = 2) + facet_grid(`Inter-taxa correlation` ~ `Effect Size`, labeller = label_both) + theme_bw() +
  geom_errorbar(aes(ymin = lower, ymax = upper),width = 0.04) + 
  geom_line() + scale_color_nejm(labels = c("cILR", "GSVA (Gaussian Kernel)", "GSVA (Poisson Kernel)", "Proportions","ssGSEA")) + 
  labs(col = "Models", x = "Sparsity", y = "Mediaan AUC (10 data sets) with HD intervals")
auc_plot

ggsave(auc_plot, filename = "docs/manuscript/figures/auc_plots.png", dpi = 300, width = 10, height = 10)


```

```{r}
data <- readRDS(file = "objects/parameter_fit_correlation.rds")

ggplot(data, aes(x = s_rho, y = mean, col = distr, linetype = adj)) + geom_line() + geom_point() + scale_color_npg(labels = c("Mixture normal", "Normal")) +
    facet_grid(eval~., scales = "free_y") + theme_bw() +
    labs(x = "Inter-taxa correlation", y = "10% trimmed mean (10 repeats)", col = "Distribution", linetype = "Adjusted")


```