source("../../method/VAM.R", chdir=T)
library(ROCR)
library(GSVA)

#
# Simulates sparse log-normal data to approximate the normalized scRNA-seq counts 
# generated by methods like Seurat NormalizeData()
# 
simulateData = function(n = 1000, p = 100,
    null.mean = 0.642, null.sd = 0.34, # based on PBMC scRNA-seq data 
    n.inflate = 50, p.inflate = 10,
    inflate.mean = 1, inflate.sd=.34,
    sparsity=0.9) {
  
  # Simulate normal data to reflect the approximately normal output from NormalizeData
  data = matrix(exp(rnorm(n*p, mean=null.mean, sd=null.sd)), nrow=n, ncol=p)
  
  # Set variable labels to column number
  colnames(data) = 1:p
  
  # Sparsify
  if (sparsity > 0) {
    zero.counts = sample(1:(n*p), n*p*sparsity, replace=F)	
    data[zero.counts] = 0
  }

  results = list()
  results$data = data
  results$inflate.data = data
  
  # Set nonzero counts for some cells to values with larger mean 
  if (n.inflate > 0) {
    nonzero = which(data[1:n.inflate,1:p.inflate] > 0)
#    results$inflate.data[1:n.inflate,1:p.inflate][nonzero] = 
#          results$inflate.data[1:n.inflate,1:p.inflate][nonzero] * exp(abs(rnorm(length(nonzero), mean=0, sd=inflate.sd)))                 
#        #mean=inflate.mean, sd=inflate.sd)))
    results$inflate.data[1:n.inflate,1:p.inflate][nonzero] = exp(rnorm(length(nonzero), mean=inflate.mean, sd=inflate.sd))
  } 
  
  return (results) 
}

#
# Generate cell-specific scores for pathway using various methods.
#
computeCellScores = function(data, inflate.data, p.set=20) {
  
  n=nrow(data)
  
  # Subset the data for the gene set
  data.set = inflate.data[,1:p.set]
  inflate.data.set = inflate.data[,1:p.set]  
  inflate.means.set = apply(inflate.data.set, 2, mean)
  
  # Compute variances of genes in pre-inflated data
  variances = apply(data.set, 2, var)
    
  scores=list()
  
  # Compute various versions of the Mahalanobis distance
  start.time = Sys.time()
  vam.results = vam(gene.expr=inflate.data.set, center=F, tech.var=variances, gamma=T) 
  scores$vam = vam.results$cdf.value
  scores$vam.time = Sys.time() - start.time

  start.time = Sys.time()    
  vam.results = vam(gene.expr=inflate.data.set, center=F, gamma=T)   
  scores$vam.full.cov = vam.results$cdf.value
  scores$vam.full.cov.time = Sys.time() - start.time
  
  # Compute GSVA scores
  start.time = Sys.time()
  scores$gsva = t(gsva(expr=t(inflate.data),
          gset.idx.list=list(set1=1:p.set),
          method="gsva",
          kcdf="Gaussian"))
  scores$gsva.time = Sys.time() - start.time
  
  # Compute ssGSEA scores
  start.time = Sys.time()
  scores$ssgsea = t(gsva(expr=t(inflate.data),
          gset.idx.list=list(set1=1:p.set),
          method="ssgsea"))
  scores$ssgsea.time = Sys.time() - start.time
  
  # Compute plage scores 
  start.time = Sys.time()
  scores$plage = t(gsva(expr=t(inflate.data),
          gset.idx.list=list(set1=1:p.set),
          method="plage"))  
  scores$plage.time = Sys.time() - start.time
  
  # Compute zscore scores
  start.time = Sys.time()
  scores$zscore = t(gsva(expr=t(inflate.data),
          gset.idx.list=list(set1=1:p.set),
          method="zscore"))    
  scores$zscore.time = Sys.time() - start.time
    
  return (scores)
}

#
# Generate cell-specific scores for pathway using various methods and compute AUC
#
computeAUCs = function(data, inflate.data, p.set=20, n.inflate=50) {
  
  n = nrow(data)
  scores = computeCellScores(data, inflate.data, p.set)
    
  # Compute AUCs
  labels = c(rep(1, n.inflate), rep(0, n-n.inflate))
  aucs = list()
  aucs$vam = performance(prediction(scores$vam, labels),"auc")@y.values[[1]]  
  #aucs$vam.full.cov = performance(prediction(scores$vam.full.cov, labels),"auc")@y.values[[1]]  
  aucs$gsva = performance(prediction(scores$gsva, labels),"auc")@y.values[[1]]
  aucs$ssgsea = performance(prediction(scores$ssgsea, labels),"auc")@y.values[[1]]
  aucs$plage = performance(prediction(abs(scores$plage), labels),"auc")@y.values[[1]]  
  aucs$zscore = performance(prediction(scores$zscore, labels),"auc")@y.values[[1]]    
  
  aucs$vam.time = scores$vam.time
  #aucs$vam.full.cov.time = scores$vam.full.cov.time
  aucs$gsva.time = scores$gsva.time
  aucs$ssgsea.time = scores$ssgsea.time  
  aucs$plage.time = scores$plage.time  
  aucs$zscore.time = scores$zscore.time    
  
  return (aucs)
}

